Repository mteu/php-template, pull requests merged in 2023-06, with the labels that each got.

#32 [FEATURE] Remove `.ddev` support
  README.md
  config.yaml
  templates/next-steps.html.twig
  templates/src/.ddev/config.yaml.twig
Labels: enhancement, breaking

#33 [FEATURE] Add GitHub action templates
  config.yaml
  templates/src/.github/ISSUE_TEMPLATE/bug_report.yml
  templates/src/.github/ISSUE_TEMPLATE/config.yml
  templates/src/.github/ISSUE_TEMPLATE/feature_request.yml
  templates/src/.github/release.yml
  templates/src/.github/workflows/cgl.yaml.twig
  templates/src/.github/workflows/release.yaml
Labels: enhancement

#34 [TASK] Rephrase project description
  README.md
  composer.json
Labels: maintenance

#35 [DOCS] Add example image of template selection
  README.md
  assets/template-selection.png
Labels: documentation

#38 [BUGFIX] Remove unnecessary twig filter
  templates/src/.github/workflows/cgl.yaml.twig
  templates/src/rector.php.twig
Labels: bug

#37 [DOCS] Correct link to offical project-builder documentation
  README.md
Labels: documentation

#39 [DOCS] Fix contribution instructions to clone repository
  CONTRIBUTING.md
Labels: documentation

#40 [DOCS] Updated 'Getting Started' section
  README.md
Labels: documentation

#46 [BUGFIX] Validate Composer package name against regex pattern
  config.yaml
Labels: bug

#47 [FEATURE] Offer a Github default value for the project url
  config.yaml
Labels: enhancement

#48 [BUGFIX] Add friendsofphp/php-cs-fixer back
  templates/src/composer.json.twig
Labels: bug
